# Generated by Django 5.2.3 on 2025-06-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=20, verbose_name='Выборка')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
