# Generated by Django 5.2.3 on 2025-07-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_project_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
    ]
